### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by JuhQ** [Vanamo/DiaryApp#1]
Huomioita käytettävyydestä
  - Kuten demoillessa huomattiin ja käytiin suullisesti läpi, joitain pieniä lapsuksia oli vielä, liittyen lähinnä kalenterinäkymään
  - Tykkäsin applikaation tyylistä monella tapaa - nykyään monet applikaatiot on saman näköisiä, ei esim uskalleta käyttää muuta fonttia kuin helveticaa
  - olisi ollut jees jos applikaatiolla olisi voinut ottaa myös kuvia
    - tykkäsin kuitenkin siitä kamerarullan ui:sta, se oli toimiva
  - haku oli jees
    - olisikohan siinä voinut olla myös haku ajan mukaan
  - kalenterissa pystyi inputissa vaihtamaan kuukautta, mutta se oli tekstikenttänä vähän epäintuitiivinen
    - jonkun sortin datepicker/rulla olisi toiminut ehkä paremmin

Kommentteja koodista
  - firebase on tosi jees!
  - App.js tiedostosta löytyy tämmöinen rivi
    ```
    monthNames: ['Tammikuu', 'Helmikuu', 'Maaliskuu', 'Huhtikuu', 'Toukokuu', 'Kesäkuu',
      'Heinäkuu', 'Elokuu', 'Syyskuu', ' Lokakuu', 'Marraskuu', ' Joulukuu'],
    ```
    tämä olisi luettavampi muodossa

    ```
    monthNames: [
      'Tammikuu',
      'Helmikuu',
      'Maaliskuu',
      'Huhtikuu',
      'Toukokuu',
      'Kesäkuu',
      'Heinäkuu',
      'Elokuu',
      'Syyskuu',
      ' Lokakuu',
      'Marraskuu',
      ' Joulukuu'
    ],
    ```
      - rivejä on toki enemmän mutta näkee silmäilemällä kaiken
      - loka- ja joulukuussa olevat välilyönnit näkyy myös näin lähes välittömästi
  - testejä olisi ollut kiva nähdä enemmän, nyt oli vaan App.test.js joka katsoo vaan ettei sovellus kaadu
  - Mikäli tulee tilanne vastaan jossa on monen rivin html tagi, kannattaa laittaa sen tagin sulkumerkki (>) samalle sisennykselle avausmerkin (<) kanssa, jotta silmäilemällä näet nopeammin mistä tagi alkaa ja minne se loppuu
    - esim utils/Loader.js
    ```
    <Modal
      transparent={true}
      animationType={'none'}
      visible={loading}
      onRequestClose={() => { console.log('close modal') }}>
    ```
    muotoon
    ```
    <Modal
      transparent={true}
      animationType={'none'}
      visible={loading}
      onRequestClose={() => { console.log('close modal') }}
    >
    ```
      - myöskin kannattaa aina debuggaamisen jälkeen poistaa console logit
        - esim tässä kohtaa huomataan että modalin sulkeutumisessa ei ole muuta kuin console log, jotenka koko propertyn voi varmaan ottaa samalla pois
      - osassa olikin sulkumerkki samalla rivillä, kannattaa pitää kuitenkin huoli että koodi on läpi projektin yhteneväinen, tämä nopeuttaa koodin läpikäyntiä, varsinkin jos projektissa olisi mukana muita
  - object destructuroinnin voi myös tehdä jo funktiomäärityksessä, esim services/auth.js
    ```
    const login = (data, callback) => {
      const { email, password } = data
      auth.signInWithEmailAndPassword(email, password)
        .then((resp) => getUser(resp.user, callback))
        .catch((error) => callback(false, null, error))
    }
    ```
    voisi muuttaa muotoon
    ```
    const login = ({ email, password }, callback) => {
      auth.signInWithEmailAndPassword(email, password)
        .then((resp) => getUser(resp.user, callback))
        .catch((error) => callback(false, null, error))
    }
    ```
  - html tageissa propertyt olisi aina hyvä laittaa tuplahipsuihin
    ```
    <Icon
      name='pencil'
      type='entypo'
      color='white'
      onPress={() => navigation.navigate('NewNote')}
    />
    ```
    muotoon
    ```
    <Icon
      name="pencil"
      type="entypo"
      color="white"
      onPress={() => navigation.navigate('NewNote')}
    />
    ```
      - molemmat toimii, tuplahipsut html:n kanssa enemmän "de facto"
        - tietenkin tämäkin riippuu projektista, on tärkeää seurata projektin määrittelemiä tyyliohjeita - jossain työprojektissa saatetaan käyttää ' hipsua tuplahipsun sijaan ja se on ok
  - kun käytät natiivia array.find metodia, kannattaa myös huomioida tilanne jossa find ei välttämättä löydä mitään
    - esim `const text = note.textInputs.find(t => t.id === c.id).text` voi aiheuttaa virhetilanteen joka voi pahimmassa tilanteessa estää sivun suorituksen tästä eteenpäin
      - tämän saisi korjattua tarkistamalla että find palauttaa jotain `const text = (note.textInputs.find(t => t.id === c.id) || {text: ''}).text`
      - MDN:stä lunttaamalla huomataan että find palauttaa undefinedin jos mitään ei löydy, jolloin voidaan käyttää `or` merkintää palauttamaan fallback arvon, joka tässä tapauksessa on objekti jossa on avain text tyhjällä merkkijonolla.
        - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find
  - HomeScreen.js tiedostossa on pari jännää funktiota, `convertToDates` ja `formulateDate`. Nämä mielestän käsittelee merkkijonoa turhaan kun voisi käsitellä suoraan objektia, ellen ymmärtänyt jotain väärin. ES6 myötä voi objektille antaa dynaamisen avaimen, näin:
  ```
  const date = 123
  const palautusObjekti = {[date]: 'hello'} // {123: 'hello'}
  ```

Kaiken kaikkiaan tosi hyvää työtä! Koodi näyttää tosi hyvältä ja kurssilla opittuja asioita on sovellettu hienosti.
Muutamat tyylilliset pulmat saisi korjattua asentamalla eslintiin vaikka airbnb:n konfiguraation ja editoriin lisäosan joka joko näyttää tyylivirheet tai korjaa ne tallennuksen yhteydessä, esim prettier plugin toimii hyvin visual studio codessa.

Pahoitteluni tarkistuksen viivästymisestä.

Onnea tulevaan react native uraan! :)

**Comment by Vanamo** [comment]
Kiitos palautteesta, yritän ottaa opiksi :)
